sudo: required
branches:
  only:
   - master
services:
- docker
addons:
  apt:
    packages:
    - p7zip-full
before_script:
- docker build . -t diibugger-builder
script:
- docker run -it --rm -v ${PWD}:/project diibugger-builder make
before_deploy:
- cd $TRAVIS_BUILD_DIR/
- mkdir -p "wiiu/plugins"
- commit="$(git rev-parse --short=7 HEAD)"
- find -type f -name "*.mod" | xargs -i cp {} wiiu/plugins
- zip -r diibugger_wups_nightly_$commit.zip wiiu
- git config --local user.name "Maschell"
- git config --local user.email "Maschell@gmx.de"
- git tag "DiiBuggerWUPS-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: p3i7VMXwqTQKZ5DyCJ7Qyp4v24bAhTAOohi4VUCNhDC3iw8D1RTkg07y8WwNKGrOoQmbodDgLlRLbo1wI/8C3qckn5KyDfAP76D89utta6FJHa7BfyM5hwgPMJtbm9gsY7gv8bdlIlOeL5SOsfG632hZ1cPKX9pSYqW2dkVHCh+JriLHDs+VEpzYpjZDxrtYwAWGaOL4vH2LH0/t78oYvDIRDgwOCjX3+ccTjpJsWMxBVy3wjiV1XHjNYL7Nj0j6FHIv9AfBtCgguoxXaBVb5iDmr61fKX2iCh8H17AN7W0SU57AHShgz/Cntuwbi+DWzg3Xzd6vnBHkCQ9osQAqhGUjgZfJHU+pSeo+GaTqYrkINJDq4Y/lFdoO/K9jio1ocoIzr5EFjIdn4ritMFXby7Z5N1Xdoo/oU1Pbqsij8OrFPd+RdzCgCoQ16l4Y1oA39FcSpgxBD2HYwzvYdiSDbHAdDLd4Hpp7tC5IIWMpL040l1nuyBuw7WOi58lW4k4ql94WeOejpJBsG6Sb0Mov+Mg7J0RXYnqBpiuBBguwJMIiGBlRQ2R6+IkxlQU2bSvZMXSjlLN1u49Mkc/FqTCYbWajGsaICpVdW2Gbm2NshADkVT2Sdk+A9DoJnBaU3MRWZfOyViR7xeuV57gruPg24dLb8O6AIZmKWASV6U9exZg=
  file: diibugger_wups_nightly_$commit.zip
  on:
    repo: Maschell/DiiBuggerWUPS
